### ISSUE TITLE
Clickhouse-server terminated by SIGSEGV

### ISSUE THREAD

**Issue by jaykelin** [yandex/ClickHouse#1368]
Clickhouse version : 1.1.54245
Clickhouse Cluster : 6hosts (24core, 64GB, centos 6.8)
Clickhouse config：
[clickhouse_settings.txt](https://github.com/yandex/ClickHouse/files/1390014/clickhouse_settings.txt)
[config.txt](https://github.com/yandex/ClickHouse/files/1390021/config.txt)
[user.txt](https://github.com/yandex/ClickHouse/files/1390022/user.txt)

```sql
-- create table 
create table dal_oth_local.oa_copyright_music_scid_y on cluster kg_bi_cluster (dt_year Date, scid String, plat_state AggregateFunction(groupArray, String), user_type_state AggregateFunction(groupArray, String), is_songpay_state AggregateFunction(groupArray, String), koudian_cnt_state AggregateFunction(groupArray, Int64), danqu_buycnt_state AggregateFunction(groupArray, Int64), play_cnt_state AggregateFunction(groupArray, Int64), download_cnt_state AggregateFunction(groupArray, Int64), dt_state AggregateFunction(groupArray, Date)) engine = AggregatingMergeTree(dt_year, (dt_year, scid), 8192)

create table dal_oth.oa_copyright_music_scid_y on cluster kg_bi_cluster (dt_year Date, scid String, plat_state AggregateFunction(groupArray, String), user_type_state AggregateFunction(groupArray, String), is_songpay_state AggregateFunction(groupArray, String), koudian_cnt_state AggregateFunction(groupArray, Int64), danqu_buycnt_state AggregateFunction(groupArray, Int64), play_cnt_state AggregateFunction(groupArray, Int64), download_cnt_state AggregateFunction(groupArray, Int64), dt_state AggregateFunction(groupArray, Date)) engine = Distributed(kg_bi_cluster, dal_oth_local, oa_copyright_music_scid_y, cityHash64(scid));
```
Query script:
```shell
#!/bin/bash
start_date="$1"
end_date="$2"
while [[ $start_date < $end_date ]]
do
        query_end_date=`date -d "+1 day $start_date" +%Y-%m-%d`
        echo "Inserting data to cluster, date = $start_date start..."
        # begin time
        begin_time=$(date +%s)
        #end time
        query="insert into dal_oth.oa_copyright_music_scid_y select toDate(concat(toString(toYear(dt)), '-01-01')) as dt_year, scid, groupArrayState(plat) as plat_state, groupArrayState(user_type) as user_type_state, groupArrayState(is_songpay) as is_songpay_state, groupArrayState(koudian_cnt) as koudian_cnt_state, groupArrayState(danqu_buycnt) as danqu_buycnt_state, groupArrayState(play_cnt) as play_cnt_state, groupArrayState(download_cnt) as download_cnt_state, groupArrayState(dt) as dt_state from dal_oth.oa_copyright_music_scid_d where dt = '${start_date}' group by dt, scid"
        while true; do
                /data1/app/clickhouse/usr/bin/clickhouse-client --stacktrace --host clickhouse.cluster --user huge_insert --password ** --query "$query"
                if [ $? -ne 0 ]; then
                        echo "Inserting data to cluster, date = $start_date failed!"
                        echo "sleep 60s"
                        sleep 60s
                else
                        break;
                fi
        done
        sleep 3s
        end_time=$(date +%s)
        spend=$(expr $end_time - $begin_time)
        echo "Inserting data to cluster, date = $start_date done. take times : $spend s"
        start_date=$query_end_date
        echo "next start=$start_date and end=$end_date"
done
```
```shell
## load data to oa_copyright_music_scid_y
loader.sh 2016-01-01 2017-10-10
```
loader.sh log:
>Inserting data to cluster, date = 2015-11-09 start...
>Inserting data to cluster, date = 2015-11-09 done. take times : 49 s
>next start=2015-11-10 and end=2017-10-01
>Inserting data to cluster, date = 2015-11-10 start...
>Inserting data to cluster, date = 2015-11-10 done. take times : 45 s
>next start=2015-11-11 and end=2017-10-01
>Inserting data to cluster, date = 2015-11-11 start...
>Code: 32. DB::Exception: Attempt to read after eof: while receiving packet from <ip****>:9000
>
>Stack trace:
>0. /data1/app/clickhouse/usr/bin/clickhouse-client(StackTrace::StackTrace()+0x16) [0x28fb6a6]
>1. /data1/app/clickhouse/usr/bin/clickhouse-client(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x1f) [0x106eb4f]
>2. /data1/app/clickhouse/usr/bin/clickhouse-client(DB::throwReadAfterEOF()+0x38) [0x106ec08]
>3. /data1/app/clickhouse/usr/bin/clickhouse-client(DB::Connection::receivePacket()+0x1105) [0x2af2c95]
>4. /data1/app/clickhouse/usr/bin/clickhouse-client(DB::Client::receivePacket()+0x24) [0x10c3724]
>5. /data1/app/clickhouse/usr/bin/clickhouse-client(DB::Client::processSingleQuery(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<DB::IAST>)+0x34d) [0x10c46ed]
>6. /data1/app/clickhouse/usr/bin/clickhouse-client(DB::Client::process(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x6da) [0x10c552a]
>7. /data1/app/clickhouse/usr/bin/clickhouse-client(DB::Client::mainImpl(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x6d2) [0x10c6672]
>8. /data1/app/clickhouse/usr/bin/clickhouse-client(DB::Client::main(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x17) [0x10c6bd7]
>9. /data1/app/clickhouse/usr/bin/clickhouse-client(Poco::Util::Application::run()+0x24) [0x3286e34]
>10. /data1/app/clickhouse/usr/bin/clickhouse-client(mainEntryClickHouseClient(int, char**)+0x605) [0x109d1b5]
>11. /data1/app/clickhouse/usr/bin/clickhouse-client(main+0x155) [0x106bfa5]
>12. /lib64/libc.so.6(__libc_start_main+0xfd) [0x342141ed5d]
>13. /data1/app/clickhouse/usr/bin/clickhouse-client() [0x106b745]
>Inserting data to cluster, date = 2015-11-11 failed!
>sleep 60s
>Inserting data to cluster, date = 2015-11-11 done. take times : 158 s
>next start=2015-11-12 and end=2017-10-01
>Inserting data to cluster, date = 2015-11-12 start...
>Inserting data to cluster, date = 2015-11-12 done. take times : 52 s

superverd log info ：
>2017-10-17 17:42:53,101 INFO received SIGCLD indicating a child quit
>2017-10-17 17:42:54,028 INFO exited: clickhouse-server (terminated by SIGSEGV; not expected)
>2017-10-17 17:42:54,029 INFO received SIGCLD indicating a child quit
>2017-10-17 17:42:55,031 INFO spawned: 'clickhouse-server' with pid 16874
>2017-10-17 17:42:56,690 INFO success: clickhouse-server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Comment by ludv1x** [comment]
We have fixed SIGSEGV related to using of distributed DDL in 1.1.54289.
Could you check this behaviour in the newest version?

Also, could you provide stacktrace with SIGSEGV from `clickhouse-server.log`, please (it starts with `###`)?

**Comment by jaykelin** [comment]
@ludv1x The case described above does not print error logs in clickhouse-server.log
But in the daily operation and maintenance, print the following ERROR log,then clickhouse-server crash
> <Error> BaseDaemon: ########################################
> <Error> BaseDaemon: (from thread 1974) Received signal Segmentation fault (11).
> <Error> BaseDaemon: Address: 0x390
> <Error> BaseDaemon: 1. /data1/app/clickhouse/release/usr/bin/clickhouse-server(DB::MergeTreeDataPart::getFullPath[abi:cxx11]() const+0x24) [0x2a62e24]
> <Error> BaseDaemon: 2. /data1/app/clickhouse/release/usr/bin/clickhouse-server(DB::MergeTreeThreadBlockInputStream::getNewTask()+0x8c) [0x2a8899c]
> <Error> BaseDaemon: 3. /data1/app/clickhouse/release/usr/bin/clickhouse-server(DB::MergeTreeBaseBlockInputStream::readImpl()+0x4ea) [0x2cf618a]
> <Error> BaseDaemon: 4. /data1/app/clickhouse/release/usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x1e6) [0x2267f26]
> <Error> BaseDaemon: 5. /data1/app/clickhouse/release/usr/bin/clickhouse-server(DB::FilterBlockInputStream::readImpl()+0x1a1) [0x2b73ab1]
> <Error> BaseDaemon: 6. /data1/app/clickhouse/release/usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x1e6) [0x2267f26]
> <Error> BaseDaemon: 7. /data1/app/clickhouse/release/usr/bin/clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x1a) [0x2b72d0a]
> <Error> BaseDaemon: 8. /data1/app/clickhouse/release/usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x1e6) [0x2267f26]
> <Error> BaseDaemon: 9. /data1/app/clickhouse/release/usr/bin/clickhouse-server(DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler, (DB::StreamUnionMode)0>::loop(unsigned long)+0x13c) [0x2bb9f0c]
> <Error> BaseDaemon: 10. /data1/app/clickhouse/release/usr/bin/clickhouse-server(DB::ParallelInputsProcessor<DB::ParallelAggregatingBlockInputStream::Handler, (DB::StreamUnionMode)0>::thread(MemoryTracker*, unsigned long)+0x68) [0x2bba2d8]
> <Error> BaseDaemon: 11. /data1/app/clickhouse/release/usr/bin/clickhouse-server() [0x350095f]
> <Error> BaseDaemon: 12. /lib64/libpthread.so.0() [0x309b8079d1]

**Comment by blinkov** [comment]
@jaykelin so have this issue still persisted on newer ClickHouse builds?

**Comment by jaykelin** [comment]
@blinkov not appeared in version v1.1.54342

**Comment by blinkov** [comment]
ok, thanks
