### ISSUE TITLE
replaceAll + FixedStrings: unexpected behaviour

### ISSUE THREAD

**Issue by hatarist** [yandex/ClickHouse#214]
Seems that calling replaceAll for a FixedString makes it lose the last character regardless of the replacements.
This is reproducible in tables (i've tried Memory, TinyLog and MergeTree permanent tables) and not reproducible in the inline (not sure how to phrase it correctly) mode.

```
CREATE TABLE replace_all_bug (str FixedString(3)) ENGINE = Memory;
INSERT INTO replace_all_bug VALUES ('foo');
INSERT INTO replace_all_bug VALUES ('bao');
INSERT INTO replace_all_bug VALUES ('bar');
SELECT str, replaceAll(str, 'o', '*') AS replaced FROM replace_all_bug;

┌─str─┬─replaced─┐
│ foo │ f*       │
│ bao │ ba       │
│ bar │ ba       │
└─────┴──────────┘
```

Strings work correctly though:
```
CREATE TABLE replace_all_no_bug (str String) ENGINE = Memory;
INSERT INTO replace_all_no_bug VALUES ('foo');
INSERT INTO replace_all_no_bug VALUES ('bao');
INSERT INTO replace_all_no_bug VALUES ('bar');
SELECT str, replaceAll(str, 'o', '*') AS replaced FROM replace_all_no_bug;

┌─str─┬─replaced─┐
│ foo │ f**      │
│ bao │ ba*      │
│ bar │ bar      │
└─────┴──────────┘
```

When not reading any tables it does work as expected, too:
```
SELECT toFixedString('foo', 3) AS str, replaceAll(str, 'o', '*') AS replaced;

┌─str─┬─replaced─┐
│ foo │ f**      │
└─────┴──────────┘
```

By the way, `replaceRegexpAll` works as expected in all cases.

**Comment by artpaul** [comment]
Fixed in https://github.com/yandex/ClickHouse/commit/db294aab1afcc3a8f405f165cbb45d1821a7bdd1

**Comment by hatarist** [comment]
Hm. It seems that it arrived again (or wasn't fixed).

Reproducible on 1.1.54180 stable and 1.1.54214 testing.

```
 :) CREATE TABLE test (date Date DEFAULT today(), fs FixedString(16)) ENGINE = MergeTree(date, (date, fs), 8192);

 :) INSERT INTO test (fs) VALUES ('54db0d43009d\0\0\0\0'), ('fe2b58224766cf10')

 :) SELECT fs, replaceAll(fs, '\0', '0') FROM test;

┌─fs───────────────────┬─replaceAll(fs, \'\\0\', \'0\')─┐
│ 54db0d43009d\0\0\0\0 │ 54db0d43009d0000               │
│ fe2b58224766cf10     │ e2b58224766cf10                │
└──────────────────────┴────────────────────────────────┘
```
