### ISSUE TITLE
Type mismatch: Column has type DateTime('UTC'), got type DateTime

### ISSUE THREAD

**Issue by filimonov** [yandex/ClickHouse#2602]
Test case:
```
create table x2 ( ts_utc DateTime DEFAULT toDateTime(ts, 'UTC'), ts DateTime )Engine = MergeTree ORDER BY ts;
INSERT INTO x2(ts) values ( now() );
alter table x2 modify column ts_utc DateTime('UTC') DEFAULT toDateTime(ts, 'UTC')
select * from x2;
```

Result:
```
Received exception from server (version 1.1.54385):
Code: 53. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Type mismatch for column ts_utc. Column has type DateTime('UTC'), got type DateTime. 
```

Expected result: DateTime and DateTime with tz should be interchangable, as TZ defines only presentation, not a storage format.

**Comment by ztlpn** [comment]
That was fixed in #2400 
The fix made it into the 1.1.54388 release

**Comment by HunterSherms** [comment]
I'm still seeing this error when writing to a table with a materialized view that aggregates the max date into another table.

```
CREATE MATERIALIZED VIEW IF NOT EXISTS
${database}._${view} TO ${database}._${max_table}
    SELECT
        group_id,
        date,
        maxState(id) AS max_id,
        maxState(inserted_at) AS max_inserted_at
    FROM ${database}._${table}
    GROUP BY (group_id, date)
```

```
Column has type AggregateFunction(max, DateTime), got type AggregateFunction(max, DateTime('UTC')): while pushing to view default._local_event_max_ids_1_days, e.what() = DB::Exception
```

**Comment by TimonKK** [comment]
I got same error for MergeTree. And after that I have gotten error in each query for table. But when I execute ALTER again - it helped fix error
