### ISSUE TITLE
Missed messages with MV & Kafka engine

### ISSUE THREAD

**Issue by millin** [yandex/ClickHouse#2788]
_Server configuration:
Kafka, ReplicatedMergeTree table and MV with TO_

When CH server starts, StorageKafka tries to write to the table before it is loaded.
```log
2018.08.01 10:54:27.290699 [ 1 ] <Information> DatabaseOrdinary (kafka): Starting up tables.
2018.08.01 10:54:27.293077 [ 26 ] <Trace> StorageKafka (kafka_cons): Setting brokers: xxx.xxx.xxx.xxx:9092,xxx.xxx.xxx.xxx:9092,xxx.xxx.xxx.xxx:9092
2018.08.01 10:54:27.293086 [ 26 ] <Trace> StorageKafka (kafka_cons): Setting Group ID: group1 Client ID: clickhouse
2018.08.01 10:54:27.293632 [ 28 ] <Debug> StorageKafka (kafka_cons): Started streaming to 2 attached views
2018.08.01 10:54:27.293662 [ 28 ] <Trace> StorageKafka (kafka_cons): Creating formatted reader
2018.08.01 10:54:27.293670 [ 28 ] <Trace> StorageKafka (kafka_cons): Row delimiter is: .
...
2018.08.01 10:54:27.816359 [ 28 ] <Error> void DB::StorageKafka::streamThread(): Code: 60, e.displayText() = DB::Exception: Table default.kafka_test doesn't exist., e.what() = DB::Exception, Stack trace:

0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x48c9056]
1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x26a5f3f]
2. clickhouse-server(DB::Context::getTableImpl(std::string const&, std::string const&, DB::Exception*) const+0x2ef) [0x41540df]
3. clickhouse-server(DB::Context::getTable(std::string const&, std::string const&) const+0x5f) [0x415445f]
4. clickhouse-server(DB::StorageMaterializedView::write(std::shared_ptr<DB::IAST> const&, DB::Settings const&)+0x34) [0x4641924]
5. clickhouse-server(DB::PushingToViewsBlockOutputStream::PushingToViewsBlockOutputStream(std::string const&, std::string const&, std::shared_ptr<DB::IStorage> const&, DB::Context const&, std::shared_ptr<DB::IAST> const&, bool)+0x5f6) [0x44d4d76]
6. clickhouse-server(DB::PushingToViewsBlockOutputStream::PushingToViewsBlockOutputStream(std::string const&, std::string const&, std::shared_ptr<DB::IStorage> const&, DB::Context const&, std::shared_ptr<DB::IAST> const&, bool)+0x4fe) [0x44d4c7e]
7. clickhouse-server(DB::InterpreterInsertQuery::execute()+0x209) [0x4196069]
8. clickhouse-server(DB::StorageKafka::streamToViews()+0x642) [0x46358b2]
9. clickhouse-server(DB::StorageKafka::streamThread()+0x1db) [0x4635e3b]
10. clickhouse-server() [0x4dc5ccf]
11. /lib64/libpthread.so.0(+0x7e25) [0x7fc9cfec6e25]
12. /lib64/libc.so.6(clone+0x6d) [0x7fc9cf6eabad]
```

All messages are lost while loading of destination table is not complete:
```log
2018.08.01 10:54:46.379845 [ 3 ] <Debug> stg.kafka_test (Data): Loading data parts
2018.08.01 10:54:46.704395 [ 3 ] <Debug> stg.kafka_test (Data): Loaded data parts (14 items)
```

**Comment by vavrusa** [comment]
This should be fixed by https://github.com/yandex/ClickHouse/commit/7eb25ef55b9f016d2bf440a277251d2d3d8b4c3e

**Comment by millin** [comment]
But this issue still happens on each server restart. I'm on latest stable v18.12.17.

**Comment by millin** [comment]
v.18.14.10. Issue still not fixed...

```log
2018.10.24 09:56:08.324216 [ 34 ] {} <Error> void DB::StorageKafka::streamThread(): Code: 60, e.displayText() = DB::Exception: Table stat.kafka_log doesn't exist., e.what() = DB::Exception, Stack trace:

0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x568f456]
1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x29b940f]
2. clickhouse-server(DB::Context::getTableImpl(std::string const&, std::string const&, DB::Exception*) const+0x2ef) [0x4f45a5f]
3. clickhouse-server(DB::Context::getTable(std::string const&, std::string const&) const+0x5f) [0x4f45ddf]
4. clickhouse-server(DB::StorageMaterializedView::write(std::shared_ptr<DB::IAST> const&, DB::Settings const&)+0x34) [0x54da274]
5. clickhouse-server(DB::PushingToViewsBlockOutputStream::PushingToViewsBlockOutputStream(std::string const&, std::string const&, std::shared_ptr<DB::IStorage> const&, DB::Context const&, std::shared_ptr<DB::IAST> const&, bool)+0x2dd) [0x5325c3d]
6. clickhouse-server(DB::PushingToViewsBlockOutputStream::PushingToViewsBlockOutputStream(std::string const&, std::string const&, std::shared_ptr<DB::IStorage> const&, DB::Context const&, std::shared_ptr<DB::IAST> const&, bool)+0x61e) [0x5325f7e]
7. clickhouse-server(DB::InterpreterInsertQuery::execute()+0x1d7) [0x4f91407]
8. clickhouse-server(DB::StorageKafka::streamToViews()+0x639) [0x515bf19]
9. clickhouse-server(DB::StorageKafka::streamThread()+0x1cd) [0x515c4ed]
10. clickhouse-server(DB::BackgroundSchedulePool::TaskInfo::execute()+0xd8) [0x52af898]
11. clickhouse-server(DB::BackgroundSchedulePool::threadFunction()+0x62) [0x52b0142]
12. clickhouse-server() [0x5d95edf]
13. /lib64/libpthread.so.0(+0x7e25) [0x7f2b911c8e25]
14. /lib64/libc.so.6(clone+0x6d) [0x7f2b909e8bad]
```
