### ISSUE TITLE
DROP TABLE (and DETACH TABLE) hangs up

### ISSUE THREAD

**Issue by xmariachi** [yandex/ClickHouse#2796]
Hi, 
using Docker containers (version 1.1.54390). 

I have a KafkaEngine table created. 
```
CREATE TABLE IF NOT EXISTS ordersKafka2
(
// ... fields
)
ENGINE = Kafka('kafka:9092', 'orders', 'CHOrders', 'JSONEachRow')
``` 
when running DROP TABLE, it hung up. 
After about 15 minutes (I read it takes time sometimes), I close the client session. A new client session will see the table if I run `show tables`. If I try to run the DROP command again, I get:
```
Table dataplatform.ordersKafka is dropping or detaching right now.
```
However nothing is shown about it in the logs, apart from this message. 
I try then to detach it, and it tries... but it hangs up, and nothing extra meaningful is shown in the logs. 

Table (and topic) is very small in size, a few MBs.
Let me know if you need more info.

Complete trace logs: 
```
<Error> executeQuery: Code: 337, e.displayText() = DB::Exception: Table dataplatform.ordersKafka is dropping or detaching right now, e.what() = DB::Exception (from ip:55448) (in query: drop table ordersKafka), Stack trace:

0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x16) [0x5656556]
1. /usr/bin/clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x22) [0x2d76d42]
2. /usr/bin/clickhouse-server(DB::Context::getDDLGuard(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const+0x12a) [0x4daecca]
3. /usr/bin/clickhouse-server(DB::InterpreterDropQuery::executeToTable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, DB::ASTDropQuery::Kind, bool, bool)+0x35f) [0x4ded6cf]
4. /usr/bin/clickhouse-server(DB::InterpreterDropQuery::execute()+0x345) [0x4df1325]
5. /usr/bin/clickhouse-server() [0x4e8010b]
6. /usr/bin/clickhouse-server(DB::executeQuery(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::Context&, bool, DB::QueryProcessingStage::Enum)+0x8a) [0x4e8112a]
7. /usr/bin/clickhouse-server(DB::TCPHandler::runImpl()+0x3d7) [0x2d83867]
8. /usr/bin/clickhouse-server(DB::TCPHandler::run()+0x2b) [0x2d8470b]
9. /usr/bin/clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x584a1ef]
```

**Comment by alexey-milovidov** [comment]
@vavrusa @bocharov

**Comment by kmatt** [comment]
Similar issue. Attempting to shutdown the clickhouse-server service hangs, with last log entry:

    <Trace> StorageKafka (logs_queue): Unsubscribing from assignments

**Comment by vavrusa** [comment]
This should be fixed in https://github.com/yandex/ClickHouse/pull/3215

**Comment by v1rusw0rm** [comment]
The `DROP TABLE` query still hangs up. Also the Clickhouse server can't be stopped. I waited for 20 minutes, last log message is:
```
2019.06.13 09:47:14.777968 [ 1 ] {} <Information> Application: Shutting down storages
```
Checked versions 19.7.5.27 and 19.8.3.8.

**Comment by steezypunk** [comment]
Face similar issues with 19.8.3.8, on drop kafka table engine got this error:
`%3|1560495915.155|cppkafka|ClickHouse 19.8.3.8#consumer-3| Failed to close consumer [ClickHouse 19.8.3.8#consumer-3]: Local: Broker handle destroyed`

The query than hung up.

**Comment by filimonov** [comment]
> Face similar issues with 19.8.3.8, on drop kafka table engine got this error:
> `%3|1560495915.155|cppkafka|ClickHouse 19.8.3.8#consumer-3| Failed to close consumer [ClickHouse 19.8.3.8#consumer-3]: Local: Broker handle destroyed`
> 
> The query than hung up.

Was the engine active before unsuccessful DROP attempt? I.e. did you read some data from it before executing DROP query? (see https://github.com/yandex/ClickHouse/issues/5615#issuecomment-502102648 )

**Comment by abyss7** [comment]
@steezypunk according to the message from your log it's exactly the #5615 - will close for now as a duplicate. For further reference the initial problem with hanging shutdown in _any_ case was fixed in version 19.8+
