### ISSUE TITLE
MemoryTracking metric strange values

### ISSUE THREAD

**Issue by Yashin32** [yandex/ClickHouse#3143]
Since v18.12.13 i receive negative values in MemoryTracking when querying system.metrics table. 

```
select metric, value from system.metrics where metric = 'MemoryTracking' format Vertical
metric: MemoryTracking
value:  -6746321106
```

```
free -m
              total        used        free      shared  buff/cache   available
Mem:          15290        1531        8289         152        5469       13222
Swap:             0           0           0
```

**Comment by sivasamyk** [comment]
We are running ClickHouse version 18.12.14 revision 54407. In our case MemoryTracking metrics is behaving like a counter (it keeps increasing).  Currently it is reporting around `170GB`.

```
select metric,value from system.metrics where metric='MemoryTracking';

SELECT
    metric,
    value
FROM system.metrics
WHERE metric = 'MemoryTracking'

┌─metric─────────┬────────value─┐
│ MemoryTracking │ 183160211569 │
└────────────────┴──────────────┘

1 rows in set. Elapsed: 0.002 sec.
```
```bash
$ free -h
              total        used        free      shared  buff/cache   available
Mem:           1.9G        757M        156M         22M        1.0G        968M
Swap:            0B          0B          0B
```
Will this commit https://github.com/vavrusa/ClickHouse/commit/0652302d9ac7d0f0ffd7a14fa767e527b77a1257 fix this issue?

**Comment by alexey-milovidov** [comment]
Yes. It is fixed in 18.14.8 (this version will be released today).

**Comment by vavrusa** [comment]
It looks like there's still issues with memory tracker in 18.14.11-stable, I suspect the memory is allocated in queries but ends up being freed elsewhere, hence the discrepancy:

```
SELECT 
    metric, 
    formatReadableSize(value)
FROM system.metrics 
WHERE metric LIKE 'Memory%'

┌─metric───────────────────────────────────┬─formatReadableSize(value)─┐
│ MemoryTracking                           │ 24.27 GiB                 │
│ MemoryTrackingInBackgroundProcessingPool │ -14.52 GiB                │
│ MemoryTrackingInBackgroundSchedulePool   │ -2.84 GiB                 │
│ MemoryTrackingForMerges                  │ 30.53 MiB                 │
└──────────────────────────────────────────┴───────────────────────────┘

4 rows in set. Elapsed: 0.002 sec. 
```

But quotas are only looking at the query memory consumption, so it throws exceptions in queries even though the limit for all queries isn't really met.

**Comment by dqminh** [comment]
@alexey-milovidov should we reopen this ? The metrics are still incorrect for us.

**Comment by citrin** [comment]
I also see a negative value with ClickHouse 19.5.3.8
```
┌─metric───────────────────────────────────┬─formatReadableSize(value)─┐
│ MemoryTracking                           │ 18.63 KiB                 │
│ MemoryTrackingInBackgroundProcessingPool │ -3.58 MiB                 │
│ MemoryTrackingInBackgroundSchedulePool   │ 0.00 B                    │
│ MemoryTrackingForMerges                  │ 0.00 B                    │
└──────────────────────────────────────────┴───────────────────────────┘
```

**Comment by Nikolo** [comment]
```
SELECT 
    metric, 
    formatReadableSize(value)
FROM system.metrics 
WHERE metric LIKE 'Memory%'

┌─metric───────────────────────────────────┬─formatReadableSize(value)─┐
│ MemoryTracking                           │ 18.56 KiB                 │
│ MemoryTrackingInBackgroundProcessingPool │ -5.87 GiB                 │
│ MemoryTrackingInBackgroundSchedulePool   │ -53.49 GiB                │
│ MemoryTrackingForMerges                  │ 17.94 MiB                 │
└──────────────────────────────────────────┴───────────────────────────┘
```
```
SELECT 
    metric, 
    value
FROM system.metrics 
WHERE metric IN ('VersionInteger', 'Revision')

┌─metric─────────┬────value─┐
│ Revision       │    54420 │
│ VersionInteger │ 19008003 │
└────────────────┴──────────┘

```

**Comment by alexey-milovidov** [comment]
```
│ MemoryTrackingInBackgroundProcessingPool │ -5.87 GiB                 │
│ MemoryTrackingInBackgroundSchedulePool   │ -53.49 GiB                │
```

It's technically Ok, because BackgroundPool frees memory allocated outside.
Example:
- SELECT from MergeTree is loading index for data parts;
- "clean old parts" operation in BackgroundSchedulePool removes old parts, deallocating their indices.

**Comment by holen** [comment]
SELECT
    metric,
    formatReadableSize(value)
FROM system.metrics
WHERE metric LIKE 'Memory%'

Query id: ea4969e7-34f3-4e79-8fa1-f949043135cc

   ┌─metric────────────────────┬─formatReadableSize(value)─┐
1. │ MemoryTracking            │ 1.52 GiB                  │
2. │ MemoryTrackingUncorrected │ 12.08 MiB                 │
   └───────────────────────────┴───────────────────────────┘
ClickHouse's memory usage keeps increasing.
<img width="806" height="221" alt="Image" src="https://github.com/user-attachments/assets/4c22f58c-3488-4a89-b1cd-2d3f89f1ba3b" />
